# Generated by Django 5.0.4 on 2024-05-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='abreviation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='abreviation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='abreviation',
            new_name='abbreviation',
        ),
    ]
