# Generated by Django 5.0.4 on 2024-05-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('fantasy_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=250)),
                ('number_adress', models.CharField(max_length=5)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('date_of_fundation', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_city', to='states.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_country', to='states.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_state', to='states.state')),
            ],
        ),
    ]
