# Generated by Django 5.0.4 on 2024-05-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_sectors', '0002_alter_productionsector_type'),
        ('states', '0002_rename_abreviation_country_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('adress_number', models.CharField(max_length=5)),
                ('neighbourhood', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_city', to='states.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_country', to='states.country')),
                ('production_sector', models.ManyToManyField(related_name='employee_sector', to='production_sectors.productionsector')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_state', to='states.state')),
            ],
        ),
    ]
