# Generated by Django 5.0.4 on 2024-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('production_sectors', '0003_alter_productionsector_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='production_sector',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_sector', to='production_sectors.productionsector'),
        ),
    ]
