# Generated by Django 5.0.4 on 2024-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Stock Entry', 'Stock Entry')], max_length=20)),
                ('ordering', models.IntegerField()),
            ],
        ),
    ]
