# Generated by Django 5.0.4 on 2024-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsector',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Stock Entry', 'Stock Entry')], default='Normal', max_length=20),
        ),
    ]
