# Generated by Django 5.0.4 on 2024-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_sectors', '0002_alter_productionsector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsector',
            name='ordering',
            field=models.IntegerField(unique=True),
        ),
    ]
