# Generated by Django 5.0.4 on 2024-05-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch_production', '0001_initial'),
        ('employees', '0001_initial'),
        ('production_sectors', '0002_alter_productionsector_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('destynation_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_dest_employee', to='employees.employee')),
                ('destynation_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_dest_sector', to='production_sectors.productionsector')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_employee', to='employees.employee')),
                ('origin_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_orig_sector', to='production_sectors.productionsector')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_dispatch', to='dispatch_production.dispatchproduction')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_priority_dispatch', to='dispatch_production.dispatchproduction')),
                ('user_created', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_user', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_up_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
