# Generated by Django 5.0.4 on 2024-05-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_production', '0001_initial'),
        ('employees', '0001_initial'),
        ('production_movements', '0001_initial'),
        ('production_sectors', '0002_alter_productionsector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmovement',
            name='destynation_employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='movement_dest_employee', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='productionmovement',
            name='destynation_sector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='movement_dest_sector', to='production_sectors.productionsector'),
        ),
        migrations.AlterField(
            model_name='productionmovement',
            name='origin_sector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='movement_orig_sector', to='production_sectors.productionsector'),
        ),
        migrations.AlterField(
            model_name='productionmovement',
            name='priority',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='movement_priority_dispatch', to='dispatch_production.dispatchproduction'),
        ),
    ]
