# Generated by Django 5.0.4 on 2024-05-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('fantasy_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=250)),
                ('number_adress', models.CharField(max_length=5)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_fundation', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_city', to='states.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_country', to='states.country')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='organization.organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsidiary_state', to='states.state')),
            ],
        ),
    ]
