# Generated by Django 5.0.4 on 2024-05-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='organization.organization'),
        ),
    ]
