# Generated by Django 5.0.4 on 2024-06-19 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchproduction',
            name='user_created',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispatchproduction',
            name='user_update',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_up_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
