# Generated by Django 5.0.4 on 2024-05-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('product_caracteristics', '0001_initial'),
        ('production_sectors', '0002_alter_productionsector_type'),
        ('subsidiaries', '0002_alter_subsidiary_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('production_time', models.TimeField(blank=True, null=True)),
                ('average_production_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brand', to='product_caracteristics.brand')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group', to='product_caracteristics.group')),
                ('organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_organization', to='organization.organization')),
                ('production_sectors', models.ManyToManyField(blank=True, null=True, related_name='product_sector', to='production_sectors.productionsector')),
                ('subsidiary', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_subsidiary', to='subsidiaries.subsidiary')),
                ('unit_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_unit', to='product_caracteristics.unitmeasure')),
                ('user_created', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_user', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_up_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
